export enum WorkflowInstanceStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum WorkflowStepStatus {
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SKIPPED = 'SKIPPED',
}

export enum WorkflowActionType {
  TRIGGERED = 'TRIGGERED',
  STEP_ACTIVATED = 'STEP_ACTIVATED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMMENTED = 'COMMENTED',
  REASSIGNED = 'REASSIGNED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}
