/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PrivateWorkflowTemplatesRouteImport } from './routes/_private/workflow-templates'
import { Route as PrivateWorkflowInstancesRouteImport } from './routes/_private/workflow-instances'
import { Route as PrivateTasksRouteImport } from './routes/_private/tasks'
import { Route as PrivatePaymentsRouteImport } from './routes/_private/payments'
import { Route as PrivateLeavesRouteImport } from './routes/_private/leaves'
import { Route as PrivateExpensesRouteImport } from './routes/_private/expenses'
import { Route as PrivateEventSchemasRouteImport } from './routes/_private/event-schemas'
import { Route as PrivateAuditLogsRouteImport } from './routes/_private/audit-logs'
import { Route as PrivateWorkflowTemplatesIndexRouteImport } from './routes/_private/workflow-templates.index'
import { Route as PrivateWorkflowInstancesIndexRouteImport } from './routes/_private/workflow-instances.index'
import { Route as PrivateLeavesIndexRouteImport } from './routes/_private/leaves.index'
import { Route as PrivateExpensesIndexRouteImport } from './routes/_private/expenses.index'
import { Route as PrivateWorkflowTemplatesNewRouteImport } from './routes/_private/workflow-templates.new'
import { Route as PrivateWorkflowTemplatesTemplateIdRouteImport } from './routes/_private/workflow-templates.$templateId'
import { Route as PrivateWorkflowInstancesInstanceIdRouteImport } from './routes/_private/workflow-instances.$instanceId'
import { Route as PrivateLeavesNewRouteImport } from './routes/_private/leaves.new'
import { Route as PrivateLeavesLeaveIdRouteImport } from './routes/_private/leaves.$leaveId'
import { Route as PrivateExpensesNewRouteImport } from './routes/_private/expenses.new'
import { Route as PrivateExpensesExpenseIdRouteImport } from './routes/_private/expenses.$expenseId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateWorkflowTemplatesRoute =
  PrivateWorkflowTemplatesRouteImport.update({
    id: '/workflow-templates',
    path: '/workflow-templates',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateWorkflowInstancesRoute =
  PrivateWorkflowInstancesRouteImport.update({
    id: '/workflow-instances',
    path: '/workflow-instances',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateTasksRoute = PrivateTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivatePaymentsRoute = PrivatePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateLeavesRoute = PrivateLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateExpensesRoute = PrivateExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateEventSchemasRoute = PrivateEventSchemasRouteImport.update({
  id: '/event-schemas',
  path: '/event-schemas',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateAuditLogsRoute = PrivateAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateWorkflowTemplatesIndexRoute =
  PrivateWorkflowTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateWorkflowTemplatesRoute,
  } as any)
const PrivateWorkflowInstancesIndexRoute =
  PrivateWorkflowInstancesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateWorkflowInstancesRoute,
  } as any)
const PrivateLeavesIndexRoute = PrivateLeavesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLeavesRoute,
} as any)
const PrivateExpensesIndexRoute = PrivateExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateExpensesRoute,
} as any)
const PrivateWorkflowTemplatesNewRoute =
  PrivateWorkflowTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateWorkflowTemplatesRoute,
  } as any)
const PrivateWorkflowTemplatesTemplateIdRoute =
  PrivateWorkflowTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => PrivateWorkflowTemplatesRoute,
  } as any)
const PrivateWorkflowInstancesInstanceIdRoute =
  PrivateWorkflowInstancesInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => PrivateWorkflowInstancesRoute,
  } as any)
const PrivateLeavesNewRoute = PrivateLeavesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PrivateLeavesRoute,
} as any)
const PrivateLeavesLeaveIdRoute = PrivateLeavesLeaveIdRouteImport.update({
  id: '/$leaveId',
  path: '/$leaveId',
  getParentRoute: () => PrivateLeavesRoute,
} as any)
const PrivateExpensesNewRoute = PrivateExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PrivateExpensesRoute,
} as any)
const PrivateExpensesExpenseIdRoute =
  PrivateExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => PrivateExpensesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/audit-logs': typeof PrivateAuditLogsRoute
  '/event-schemas': typeof PrivateEventSchemasRoute
  '/expenses': typeof PrivateExpensesRouteWithChildren
  '/leaves': typeof PrivateLeavesRouteWithChildren
  '/payments': typeof PrivatePaymentsRoute
  '/tasks': typeof PrivateTasksRoute
  '/workflow-instances': typeof PrivateWorkflowInstancesRouteWithChildren
  '/workflow-templates': typeof PrivateWorkflowTemplatesRouteWithChildren
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/expenses/$expenseId': typeof PrivateExpensesExpenseIdRoute
  '/expenses/new': typeof PrivateExpensesNewRoute
  '/leaves/$leaveId': typeof PrivateLeavesLeaveIdRoute
  '/leaves/new': typeof PrivateLeavesNewRoute
  '/workflow-instances/$instanceId': typeof PrivateWorkflowInstancesInstanceIdRoute
  '/workflow-templates/$templateId': typeof PrivateWorkflowTemplatesTemplateIdRoute
  '/workflow-templates/new': typeof PrivateWorkflowTemplatesNewRoute
  '/expenses/': typeof PrivateExpensesIndexRoute
  '/leaves/': typeof PrivateLeavesIndexRoute
  '/workflow-instances/': typeof PrivateWorkflowInstancesIndexRoute
  '/workflow-templates/': typeof PrivateWorkflowTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/audit-logs': typeof PrivateAuditLogsRoute
  '/event-schemas': typeof PrivateEventSchemasRoute
  '/payments': typeof PrivatePaymentsRoute
  '/tasks': typeof PrivateTasksRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/expenses/$expenseId': typeof PrivateExpensesExpenseIdRoute
  '/expenses/new': typeof PrivateExpensesNewRoute
  '/leaves/$leaveId': typeof PrivateLeavesLeaveIdRoute
  '/leaves/new': typeof PrivateLeavesNewRoute
  '/workflow-instances/$instanceId': typeof PrivateWorkflowInstancesInstanceIdRoute
  '/workflow-templates/$templateId': typeof PrivateWorkflowTemplatesTemplateIdRoute
  '/workflow-templates/new': typeof PrivateWorkflowTemplatesNewRoute
  '/expenses': typeof PrivateExpensesIndexRoute
  '/leaves': typeof PrivateLeavesIndexRoute
  '/workflow-instances': typeof PrivateWorkflowInstancesIndexRoute
  '/workflow-templates': typeof PrivateWorkflowTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/audit-logs': typeof PrivateAuditLogsRoute
  '/_private/event-schemas': typeof PrivateEventSchemasRoute
  '/_private/expenses': typeof PrivateExpensesRouteWithChildren
  '/_private/leaves': typeof PrivateLeavesRouteWithChildren
  '/_private/payments': typeof PrivatePaymentsRoute
  '/_private/tasks': typeof PrivateTasksRoute
  '/_private/workflow-instances': typeof PrivateWorkflowInstancesRouteWithChildren
  '/_private/workflow-templates': typeof PrivateWorkflowTemplatesRouteWithChildren
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/expenses/$expenseId': typeof PrivateExpensesExpenseIdRoute
  '/_private/expenses/new': typeof PrivateExpensesNewRoute
  '/_private/leaves/$leaveId': typeof PrivateLeavesLeaveIdRoute
  '/_private/leaves/new': typeof PrivateLeavesNewRoute
  '/_private/workflow-instances/$instanceId': typeof PrivateWorkflowInstancesInstanceIdRoute
  '/_private/workflow-templates/$templateId': typeof PrivateWorkflowTemplatesTemplateIdRoute
  '/_private/workflow-templates/new': typeof PrivateWorkflowTemplatesNewRoute
  '/_private/expenses/': typeof PrivateExpensesIndexRoute
  '/_private/leaves/': typeof PrivateLeavesIndexRoute
  '/_private/workflow-instances/': typeof PrivateWorkflowInstancesIndexRoute
  '/_private/workflow-templates/': typeof PrivateWorkflowTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/event-schemas'
    | '/expenses'
    | '/leaves'
    | '/payments'
    | '/tasks'
    | '/workflow-instances'
    | '/workflow-templates'
    | '/sign-in'
    | '/sign-up'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/leaves/$leaveId'
    | '/leaves/new'
    | '/workflow-instances/$instanceId'
    | '/workflow-templates/$templateId'
    | '/workflow-templates/new'
    | '/expenses/'
    | '/leaves/'
    | '/workflow-instances/'
    | '/workflow-templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/event-schemas'
    | '/payments'
    | '/tasks'
    | '/sign-in'
    | '/sign-up'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/leaves/$leaveId'
    | '/leaves/new'
    | '/workflow-instances/$instanceId'
    | '/workflow-templates/$templateId'
    | '/workflow-templates/new'
    | '/expenses'
    | '/leaves'
    | '/workflow-instances'
    | '/workflow-templates'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/audit-logs'
    | '/_private/event-schemas'
    | '/_private/expenses'
    | '/_private/leaves'
    | '/_private/payments'
    | '/_private/tasks'
    | '/_private/workflow-instances'
    | '/_private/workflow-templates'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_private/'
    | '/_private/expenses/$expenseId'
    | '/_private/expenses/new'
    | '/_private/leaves/$leaveId'
    | '/_private/leaves/new'
    | '/_private/workflow-instances/$instanceId'
    | '/_private/workflow-templates/$templateId'
    | '/_private/workflow-templates/new'
    | '/_private/expenses/'
    | '/_private/leaves/'
    | '/_private/workflow-instances/'
    | '/_private/workflow-templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/workflow-templates': {
      id: '/_private/workflow-templates'
      path: '/workflow-templates'
      fullPath: '/workflow-templates'
      preLoaderRoute: typeof PrivateWorkflowTemplatesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/workflow-instances': {
      id: '/_private/workflow-instances'
      path: '/workflow-instances'
      fullPath: '/workflow-instances'
      preLoaderRoute: typeof PrivateWorkflowInstancesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/tasks': {
      id: '/_private/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof PrivateTasksRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/payments': {
      id: '/_private/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PrivatePaymentsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/leaves': {
      id: '/_private/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof PrivateLeavesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/expenses': {
      id: '/_private/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof PrivateExpensesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/event-schemas': {
      id: '/_private/event-schemas'
      path: '/event-schemas'
      fullPath: '/event-schemas'
      preLoaderRoute: typeof PrivateEventSchemasRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/audit-logs': {
      id: '/_private/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof PrivateAuditLogsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/workflow-templates/': {
      id: '/_private/workflow-templates/'
      path: '/'
      fullPath: '/workflow-templates/'
      preLoaderRoute: typeof PrivateWorkflowTemplatesIndexRouteImport
      parentRoute: typeof PrivateWorkflowTemplatesRoute
    }
    '/_private/workflow-instances/': {
      id: '/_private/workflow-instances/'
      path: '/'
      fullPath: '/workflow-instances/'
      preLoaderRoute: typeof PrivateWorkflowInstancesIndexRouteImport
      parentRoute: typeof PrivateWorkflowInstancesRoute
    }
    '/_private/leaves/': {
      id: '/_private/leaves/'
      path: '/'
      fullPath: '/leaves/'
      preLoaderRoute: typeof PrivateLeavesIndexRouteImport
      parentRoute: typeof PrivateLeavesRoute
    }
    '/_private/expenses/': {
      id: '/_private/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof PrivateExpensesIndexRouteImport
      parentRoute: typeof PrivateExpensesRoute
    }
    '/_private/workflow-templates/new': {
      id: '/_private/workflow-templates/new'
      path: '/new'
      fullPath: '/workflow-templates/new'
      preLoaderRoute: typeof PrivateWorkflowTemplatesNewRouteImport
      parentRoute: typeof PrivateWorkflowTemplatesRoute
    }
    '/_private/workflow-templates/$templateId': {
      id: '/_private/workflow-templates/$templateId'
      path: '/$templateId'
      fullPath: '/workflow-templates/$templateId'
      preLoaderRoute: typeof PrivateWorkflowTemplatesTemplateIdRouteImport
      parentRoute: typeof PrivateWorkflowTemplatesRoute
    }
    '/_private/workflow-instances/$instanceId': {
      id: '/_private/workflow-instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/workflow-instances/$instanceId'
      preLoaderRoute: typeof PrivateWorkflowInstancesInstanceIdRouteImport
      parentRoute: typeof PrivateWorkflowInstancesRoute
    }
    '/_private/leaves/new': {
      id: '/_private/leaves/new'
      path: '/new'
      fullPath: '/leaves/new'
      preLoaderRoute: typeof PrivateLeavesNewRouteImport
      parentRoute: typeof PrivateLeavesRoute
    }
    '/_private/leaves/$leaveId': {
      id: '/_private/leaves/$leaveId'
      path: '/$leaveId'
      fullPath: '/leaves/$leaveId'
      preLoaderRoute: typeof PrivateLeavesLeaveIdRouteImport
      parentRoute: typeof PrivateLeavesRoute
    }
    '/_private/expenses/new': {
      id: '/_private/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof PrivateExpensesNewRouteImport
      parentRoute: typeof PrivateExpensesRoute
    }
    '/_private/expenses/$expenseId': {
      id: '/_private/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof PrivateExpensesExpenseIdRouteImport
      parentRoute: typeof PrivateExpensesRoute
    }
  }
}

interface PrivateExpensesRouteChildren {
  PrivateExpensesExpenseIdRoute: typeof PrivateExpensesExpenseIdRoute
  PrivateExpensesNewRoute: typeof PrivateExpensesNewRoute
  PrivateExpensesIndexRoute: typeof PrivateExpensesIndexRoute
}

const PrivateExpensesRouteChildren: PrivateExpensesRouteChildren = {
  PrivateExpensesExpenseIdRoute: PrivateExpensesExpenseIdRoute,
  PrivateExpensesNewRoute: PrivateExpensesNewRoute,
  PrivateExpensesIndexRoute: PrivateExpensesIndexRoute,
}

const PrivateExpensesRouteWithChildren = PrivateExpensesRoute._addFileChildren(
  PrivateExpensesRouteChildren,
)

interface PrivateLeavesRouteChildren {
  PrivateLeavesLeaveIdRoute: typeof PrivateLeavesLeaveIdRoute
  PrivateLeavesNewRoute: typeof PrivateLeavesNewRoute
  PrivateLeavesIndexRoute: typeof PrivateLeavesIndexRoute
}

const PrivateLeavesRouteChildren: PrivateLeavesRouteChildren = {
  PrivateLeavesLeaveIdRoute: PrivateLeavesLeaveIdRoute,
  PrivateLeavesNewRoute: PrivateLeavesNewRoute,
  PrivateLeavesIndexRoute: PrivateLeavesIndexRoute,
}

const PrivateLeavesRouteWithChildren = PrivateLeavesRoute._addFileChildren(
  PrivateLeavesRouteChildren,
)

interface PrivateWorkflowInstancesRouteChildren {
  PrivateWorkflowInstancesInstanceIdRoute: typeof PrivateWorkflowInstancesInstanceIdRoute
  PrivateWorkflowInstancesIndexRoute: typeof PrivateWorkflowInstancesIndexRoute
}

const PrivateWorkflowInstancesRouteChildren: PrivateWorkflowInstancesRouteChildren =
  {
    PrivateWorkflowInstancesInstanceIdRoute:
      PrivateWorkflowInstancesInstanceIdRoute,
    PrivateWorkflowInstancesIndexRoute: PrivateWorkflowInstancesIndexRoute,
  }

const PrivateWorkflowInstancesRouteWithChildren =
  PrivateWorkflowInstancesRoute._addFileChildren(
    PrivateWorkflowInstancesRouteChildren,
  )

interface PrivateWorkflowTemplatesRouteChildren {
  PrivateWorkflowTemplatesTemplateIdRoute: typeof PrivateWorkflowTemplatesTemplateIdRoute
  PrivateWorkflowTemplatesNewRoute: typeof PrivateWorkflowTemplatesNewRoute
  PrivateWorkflowTemplatesIndexRoute: typeof PrivateWorkflowTemplatesIndexRoute
}

const PrivateWorkflowTemplatesRouteChildren: PrivateWorkflowTemplatesRouteChildren =
  {
    PrivateWorkflowTemplatesTemplateIdRoute:
      PrivateWorkflowTemplatesTemplateIdRoute,
    PrivateWorkflowTemplatesNewRoute: PrivateWorkflowTemplatesNewRoute,
    PrivateWorkflowTemplatesIndexRoute: PrivateWorkflowTemplatesIndexRoute,
  }

const PrivateWorkflowTemplatesRouteWithChildren =
  PrivateWorkflowTemplatesRoute._addFileChildren(
    PrivateWorkflowTemplatesRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateAuditLogsRoute: typeof PrivateAuditLogsRoute
  PrivateEventSchemasRoute: typeof PrivateEventSchemasRoute
  PrivateExpensesRoute: typeof PrivateExpensesRouteWithChildren
  PrivateLeavesRoute: typeof PrivateLeavesRouteWithChildren
  PrivatePaymentsRoute: typeof PrivatePaymentsRoute
  PrivateTasksRoute: typeof PrivateTasksRoute
  PrivateWorkflowInstancesRoute: typeof PrivateWorkflowInstancesRouteWithChildren
  PrivateWorkflowTemplatesRoute: typeof PrivateWorkflowTemplatesRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAuditLogsRoute: PrivateAuditLogsRoute,
  PrivateEventSchemasRoute: PrivateEventSchemasRoute,
  PrivateExpensesRoute: PrivateExpensesRouteWithChildren,
  PrivateLeavesRoute: PrivateLeavesRouteWithChildren,
  PrivatePaymentsRoute: PrivatePaymentsRoute,
  PrivateTasksRoute: PrivateTasksRoute,
  PrivateWorkflowInstancesRoute: PrivateWorkflowInstancesRouteWithChildren,
  PrivateWorkflowTemplatesRoute: PrivateWorkflowTemplatesRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
